# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
cache: packages

os:
  - osx
  - linux

warning_are_error: true

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
